#!/bin/bash

echo "🚀 Building Flutter web app for GitHub Pages..."
npm run build:secure

echo "📦 Preparing for GitHub Pages deployment..."
echo "✅ Build completed successfully!"
echo ""
echo "🌐 To deploy to GitHub Pages:"
echo "1. Push your code to GitHub:"
echo "   git add ."
echo "   git commit -m 'Add GitHub Pages deployment'"
echo "   git push origin main"
echo ""
echo "2. Go to your GitHub repository settings:"
echo "   - Navigate to Settings > Pages"
echo "   - Set source to 'GitHub Actions'"
echo "   - Add Firebase secrets to repository secrets"
echo ""
echo "3. Your app will be available at:"
echo "   https://[your-username].github.io/[repository-name]/"
echo ""
echo "📝 Required GitHub Secrets:"
echo "   FIREBASE_API_KEY"
echo "   FIREBASE_AUTH_DOMAIN"
echo "   FIREBASE_DATABASE_URL"
echo "   FIREBASE_PROJECT_ID"
echo "   FIREBASE_STORAGE_BUCKET"
echo "   FIREBASE_MESSAGING_SENDER_ID"
echo "   FIREBASE_APP_ID"
echo "   FIREBASE_MEASUREMENT_ID" 