name: fp_design
description: A design system for FP
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.3.0
  widgetbook_annotation: ^2.0.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^4.0.0-alpha.2
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  test: ^1.24.9
  mockito: ^5.4.4
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.otf
          weight: 400
        - asset: assets/fonts/Geist-Medium.otf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Geist-Bold.otf
          weight: 700 